"""init

Revision ID: 11ded6ad709c
Revises: 
Create Date: 2026-01-21 17:02:20.461241

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision = "11ded6ad709c"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name='uq_users_email')
    )
    op.create_table('connected_accounts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('access_token_enc', sa.String(length=2000), nullable=False),
    sa.Column('refresh_token_enc', sa.String(length=2000), nullable=False),
    sa.Column('scopes', postgresql.ARRAY(sa.String(length=200)), nullable=False),
    sa.Column('token_expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_connected_accounts_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_connected_accounts')),
    sa.UniqueConstraint('provider', 'provider_account_id', name='uq_connected_provider_account')
    )
    op.create_table('evidence_emails',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_message_id', sa.String(length=255), nullable=False),
    sa.Column('from_address', sa.String(length=320), nullable=False),
    sa.Column('from_domain', sa.String(length=255), nullable=False),
    sa.Column('subject', sa.Text(), nullable=False),
    sa.Column('snippet', sa.Text(), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('evidence_type', sa.String(length=50), nullable=False),
    sa.Column('raw_headers', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_evidence_emails_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_evidence_emails')),
    sa.UniqueConstraint('provider', 'provider_message_id', name='uq_evidence_provider_message')
    )
    op.create_index('ix_evidence_user_domain', 'evidence_emails', ['user_id', 'from_domain'], unique=False)
    op.create_index('ix_evidence_user_sent_at', 'evidence_emails', ['user_id', 'sent_at'], unique=False)
    op.create_table('services',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('display_name', sa.String(length=200), nullable=False),
    sa.Column('primary_domain', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('confidence', sa.String(length=20), nullable=False),
    sa.Column('confidence_reason', sa.Text(), nullable=False),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_services_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_services')),
    sa.UniqueConstraint('user_id', 'primary_domain', name='uq_services_user_domain')
    )
    op.create_index('ix_services_user_confidence', 'services', ['user_id', 'confidence'], unique=False)
    op.create_table('scan_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('connected_account_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['connected_account_id'], ['connected_accounts.id'], name=op.f('fk_scan_runs_connected_account_id_connected_accounts')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scan_runs_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_scan_runs'))
    )
    op.create_index('ix_scan_runs_user_status', 'scan_runs', ['user_id', 'status'], unique=False)
    op.create_table('service_evidence_links',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('service_id', sa.UUID(), nullable=False),
    sa.Column('evidence_email_id', sa.UUID(), nullable=False),
    sa.Column('match_reason', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_email_id'], ['evidence_emails.id'], name=op.f('fk_service_evidence_links_evidence_email_id_evidence_emails')),
    sa.ForeignKeyConstraint(['service_id'], ['services.id'], name=op.f('fk_service_evidence_links_service_id_services')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_evidence_links')),
    sa.UniqueConstraint('service_id', 'evidence_email_id', name='uq_service_evidence_link')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('service_evidence_links')
    op.drop_index('ix_scan_runs_user_status', table_name='scan_runs')
    op.drop_table('scan_runs')
    op.drop_index('ix_services_user_confidence', table_name='services')
    op.drop_table('services')
    op.drop_index('ix_evidence_user_sent_at', table_name='evidence_emails')
    op.drop_index('ix_evidence_user_domain', table_name='evidence_emails')
    op.drop_table('evidence_emails')
    op.drop_table('connected_accounts')
    op.drop_table('users')
    # ### end Alembic commands ###
