"""add scan progress and service aliases

Revision ID: feaad770a841
Revises: 11ded6ad709c
Create Date: 2026-02-06 17:41:14.611453

"""
from alembic import op
import sqlalchemy as sa


revision = "feaad770a841"
down_revision = '11ded6ad709c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('service_aliases',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('service_name', sa.String(length=200), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_service_aliases')),
    sa.UniqueConstraint('domain', name='uq_service_alias_domain')
    )
    op.add_column(
        'scan_runs',
        sa.Column('processed_count', sa.Integer(), server_default=sa.text('0'), nullable=False)
    )
    op.add_column('scan_runs', sa.Column('total_estimated', sa.Integer(), nullable=True))
    op.add_column('scan_runs', sa.Column('progress_pct', sa.Float(), nullable=True))
    op.add_column('scan_runs', sa.Column('next_page_token', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('scan_runs', 'next_page_token')
    op.drop_column('scan_runs', 'progress_pct')
    op.drop_column('scan_runs', 'total_estimated')
    op.drop_column('scan_runs', 'processed_count')
    op.drop_table('service_aliases')
    # ### end Alembic commands ###
